"""Auto-generated migration

Revision ID: 09a4696dc534
Revises: 405b7163d999
Create Date: 2024-10-23 11:07:27.425692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09a4696dc534'
down_revision: Union[str, None] = '405b7163d999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('news_articles', sa.Column('reg_date', sa.Date(), nullable=True))
    op.drop_column('news_articles', 'updated_at')
    op.drop_column('news_articles', 'created_at')
    op.drop_column('news_articles', 'source')
    op.drop_column('news_articles', 'status')
    op.drop_column('news_articles', 'published_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('published_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('news_articles', 'reg_date')
    op.drop_column('news_articles', 'thumbnail')
    # ### end Alembic commands ###
