"""Auto-generated migration

Revision ID: 0a64d5aba7b3
Revises: 0c1e99473b7f
Create Date: 2024-09-29 03:32:15.463941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a64d5aba7b3'
down_revision: Union[str, None] = '0c1e99473b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_region',
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('region_name_kor', sa.String(), nullable=True),
    sa.Column('region_name_eng', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_index(op.f('ix_kb_region_region_code'), 'kb_region', ['region_code'], unique=False)
    op.create_index(op.f('ix_kb_region_region_name_eng'), 'kb_region', ['region_name_eng'], unique=True)
    op.create_index(op.f('ix_kb_region_region_name_kor'), 'kb_region', ['region_name_kor'], unique=True)
    op.create_table('kb_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price_type', sa.String(), nullable=True),
    sa.Column('predicted_index', sa.Float(), nullable=True),
    sa.Column('predicted_price', sa.Float(), nullable=True),
    sa.Column('prediction_accuracies', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_code'], ['kb_region.region_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_prediction_date'), 'kb_prediction', ['date'], unique=False)
    op.create_index(op.f('ix_kb_prediction_id'), 'kb_prediction', ['id'], unique=False)
    op.create_table('kb_property_price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price_type', sa.String(), nullable=True),
    sa.Column('index_value', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('is_interpolated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['region_code'], ['kb_region.region_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_property_price_data_date'), 'kb_property_price_data', ['date'], unique=False)
    op.create_index(op.f('ix_kb_property_price_data_id'), 'kb_property_price_data', ['id'], unique=False)
    op.create_index(op.f('ix_kb_property_price_data_price_type'), 'kb_property_price_data', ['price_type'], unique=False)
    op.create_index('ix_region_date_type_timespan', 'kb_property_price_data', ['region_code', 'date', 'price_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_region_date_type_timespan', table_name='kb_property_price_data')
    op.drop_index(op.f('ix_kb_property_price_data_price_type'), table_name='kb_property_price_data')
    op.drop_index(op.f('ix_kb_property_price_data_id'), table_name='kb_property_price_data')
    op.drop_index(op.f('ix_kb_property_price_data_date'), table_name='kb_property_price_data')
    op.drop_table('kb_property_price_data')
    op.drop_index(op.f('ix_kb_prediction_id'), table_name='kb_prediction')
    op.drop_index(op.f('ix_kb_prediction_date'), table_name='kb_prediction')
    op.drop_table('kb_prediction')
    op.drop_index(op.f('ix_kb_region_region_name_kor'), table_name='kb_region')
    op.drop_index(op.f('ix_kb_region_region_name_eng'), table_name='kb_region')
    op.drop_index(op.f('ix_kb_region_region_code'), table_name='kb_region')
    op.drop_table('kb_region')
    # ### end Alembic commands ###
