"""Auto-generated migration

Revision ID: 0c1e99473b7f
Revises: ae754bd338fa
Create Date: 2024-09-29 03:27:16.353285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1e99473b7f'
down_revision: Union[str, None] = 'ae754bd338fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_prediction', sa.Column('region_code', sa.String(), nullable=True))
    op.add_column('kb_prediction', sa.Column('prediction_accuracies', sa.Float(), nullable=True))
    op.drop_constraint('kb_prediction_region_id_fkey', 'kb_prediction', type_='foreignkey')
    op.create_foreign_key(None, 'kb_prediction', 'kb_region', ['region_code'], ['region_code'])
    op.drop_column('kb_prediction', 'region_id')
    op.drop_column('kb_prediction', 'prediction_accuracy')
    op.add_column('kb_property_price_data', sa.Column('region_code', sa.String(), nullable=True))
    op.drop_index('ix_region_date_type_timespan', table_name='kb_property_price_data')
    op.create_index('ix_region_date_type_timespan', 'kb_property_price_data', ['region_code', 'date', 'price_type'], unique=False)
    op.drop_constraint('kb_property_price_data_region_id_fkey', 'kb_property_price_data', type_='foreignkey')
    op.create_foreign_key(None, 'kb_property_price_data', 'kb_region', ['region_code'], ['region_code'])
    op.drop_column('kb_property_price_data', 'region_id')
    op.alter_column('kb_region', 'region_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_kb_region_id', table_name='kb_region')
    op.drop_index('ix_kb_region_region_code', table_name='kb_region')
    op.create_index(op.f('ix_kb_region_region_code'), 'kb_region', ['region_code'], unique=False)
    op.drop_column('kb_region', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_region', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('kb_region_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_kb_region_region_code'), table_name='kb_region')
    op.create_index('ix_kb_region_region_code', 'kb_region', ['region_code'], unique=True)
    op.create_index('ix_kb_region_id', 'kb_region', ['id'], unique=False)
    op.alter_column('kb_region', 'region_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('kb_property_price_data', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'kb_property_price_data', type_='foreignkey')
    op.create_foreign_key('kb_property_price_data_region_id_fkey', 'kb_property_price_data', 'kb_region', ['region_id'], ['id'])
    op.drop_index('ix_region_date_type_timespan', table_name='kb_property_price_data')
    op.create_index('ix_region_date_type_timespan', 'kb_property_price_data', ['region_id', 'date', 'price_type'], unique=False)
    op.drop_column('kb_property_price_data', 'region_code')
    op.add_column('kb_prediction', sa.Column('prediction_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('kb_prediction', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'kb_prediction', type_='foreignkey')
    op.create_foreign_key('kb_prediction_region_id_fkey', 'kb_prediction', 'kb_region', ['region_id'], ['id'])
    op.drop_column('kb_prediction', 'prediction_accuracies')
    op.drop_column('kb_prediction', 'region_code')
    # ### end Alembic commands ###
