"""Auto-generated migration

Revision ID: 31f8738ee080
Revises: c26a2ce4d657
Create Date: 2024-09-28 16:50:27.719570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f8738ee080'
down_revision: Union[str, None] = 'c26a2ce4d657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'kb_prediction', 'kb_region', ['region_id'], ['id'])
    op.add_column('kb_property_price_data', sa.Column('is_interpolated', sa.String(), nullable=True))
    op.create_foreign_key(None, 'kb_property_price_data', 'kb_region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kb_property_price_data', type_='foreignkey')
    op.drop_column('kb_property_price_data', 'is_interpolated')
    op.drop_constraint(None, 'kb_prediction', type_='foreignkey')
    # ### end Alembic commands ###
