"""Initial migration

Revision ID: 405b7163d999
Revises: 679202f4baab
Create Date: 2024-10-23 10:56:00.792264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405b7163d999'
down_revision: Union[str, None] = '679202f4baab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('news_articles', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('news_articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('news_articles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('news_articles', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'status')
    op.drop_column('news_articles', 'updated_at')
    op.drop_column('news_articles', 'created_at')
    op.drop_column('news_articles', 'source')
    op.drop_column('news_articles', 'summary')
    # ### end Alembic commands ###
