"""Auto-generated migration

Revision ID: 89a2313bb377
Revises: f997ddc76b91
Create Date: 2024-09-28 21:53:53.881747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a2313bb377'
down_revision: Union[str, None] = 'f997ddc76b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_region_id'), 'kb_region', ['id'], unique=False)
    op.create_index(op.f('ix_kb_region_region_name'), 'kb_region', ['region_name'], unique=True)
    op.create_table('kb_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price_type', sa.String(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('prediction_accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['kb_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_prediction_date'), 'kb_prediction', ['date'], unique=False)
    op.create_index(op.f('ix_kb_prediction_id'), 'kb_prediction', ['id'], unique=False)
    op.create_table('kb_property_price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price_type', sa.String(), nullable=True),
    sa.Column('index_value', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('is_interpolated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['kb_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_property_price_data_date'), 'kb_property_price_data', ['date'], unique=False)
    op.create_index(op.f('ix_kb_property_price_data_id'), 'kb_property_price_data', ['id'], unique=False)
    op.create_index(op.f('ix_kb_property_price_data_price_type'), 'kb_property_price_data', ['price_type'], unique=False)
    op.create_index('ix_region_date_type_timespan', 'kb_property_price_data', ['region_id', 'date', 'price_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_region_date_type_timespan', table_name='kb_property_price_data')
    op.drop_index(op.f('ix_kb_property_price_data_price_type'), table_name='kb_property_price_data')
    op.drop_index(op.f('ix_kb_property_price_data_id'), table_name='kb_property_price_data')
    op.drop_index(op.f('ix_kb_property_price_data_date'), table_name='kb_property_price_data')
    op.drop_table('kb_property_price_data')
    op.drop_index(op.f('ix_kb_prediction_id'), table_name='kb_prediction')
    op.drop_index(op.f('ix_kb_prediction_date'), table_name='kb_prediction')
    op.drop_table('kb_prediction')
    op.drop_index(op.f('ix_kb_region_region_name'), table_name='kb_region')
    op.drop_index(op.f('ix_kb_region_id'), table_name='kb_region')
    op.drop_table('kb_region')
    # ### end Alembic commands ###
