"""Auto-generated migration

Revision ID: ac9ad646a45b
Revises: c015e0089dd3
Create Date: 2024-09-29 02:49:10.644790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9ad646a45b'
down_revision: Union[str, None] = 'c015e0089dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_region', sa.Column('region_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_kb_region_region_code'), 'kb_region', ['region_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_region_region_code'), table_name='kb_region')
    op.drop_column('kb_region', 'region_code')
    # ### end Alembic commands ###
