"""Auto-generated migration

Revision ID: c015e0089dd3
Revises: d2be3e407534
Create Date: 2024-09-29 02:41:16.491577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c015e0089dd3'
down_revision: Union[str, None] = 'd2be3e407534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_region', sa.Column('region_name_kor', sa.String(), nullable=True))
    op.add_column('kb_region', sa.Column('region_name_eng', sa.String(), nullable=True))
    op.drop_index('ix_kb_region_region_name', table_name='kb_region')
    op.create_index(op.f('ix_kb_region_region_name_eng'), 'kb_region', ['region_name_eng'], unique=True)
    op.create_index(op.f('ix_kb_region_region_name_kor'), 'kb_region', ['region_name_kor'], unique=True)
    op.drop_column('kb_region', 'region_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_region', sa.Column('region_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_kb_region_region_name_kor'), table_name='kb_region')
    op.drop_index(op.f('ix_kb_region_region_name_eng'), table_name='kb_region')
    op.create_index('ix_kb_region_region_name', 'kb_region', ['region_name'], unique=True)
    op.drop_column('kb_region', 'region_name_eng')
    op.drop_column('kb_region', 'region_name_kor')
    # ### end Alembic commands ###
