"""Auto-generated migration

Revision ID: d2be3e407534
Revises: 89a2313bb377
Create Date: 2024-09-28 22:14:39.135682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2be3e407534'
down_revision: Union[str, None] = '89a2313bb377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_prediction', sa.Column('predicted_index', sa.Float(), nullable=True))
    op.add_column('kb_prediction', sa.Column('predicted_price', sa.Float(), nullable=True))
    op.drop_column('kb_prediction', 'predicted_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_prediction', sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('kb_prediction', 'predicted_price')
    op.drop_column('kb_prediction', 'predicted_index')
    # ### end Alembic commands ###
