"""Auto-generated migration

Revision ID: ee004dc95e99
Revises: 588ee18ba469
Create Date: 2024-09-28 15:32:58.058584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee004dc95e99'
down_revision: Union[str, None] = '588ee18ba469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kb_property_price_data_date', table_name='kb_property_price_data')
    op.drop_index('ix_kb_property_price_data_id', table_name='kb_property_price_data')
    op.drop_index('ix_kb_property_price_data_price_type', table_name='kb_property_price_data')
    op.drop_index('ix_kb_property_price_data_time_span', table_name='kb_property_price_data')
    op.drop_table('kb_property_price_data')
    op.drop_index('ix_KB_REGION_id', table_name='KB_REGION')
    op.drop_index('ix_KB_REGION_region_name', table_name='KB_REGION')
    op.drop_table('KB_REGION')
    op.drop_index('ix_kb_region_id', table_name='kb_region')
    op.drop_index('ix_kb_region_region_name', table_name='kb_region')
    op.drop_table('kb_region')
    op.drop_index('ix_kb_prediction_date', table_name='kb_prediction')
    op.drop_index('ix_kb_prediction_id', table_name='kb_prediction')
    op.drop_table('kb_prediction')
    op.drop_index('ix_KB_PROPERTY_PRICE_DATA_date', table_name='KB_PROPERTY_PRICE_DATA')
    op.drop_index('ix_KB_PROPERTY_PRICE_DATA_id', table_name='KB_PROPERTY_PRICE_DATA')
    op.drop_index('ix_KB_PROPERTY_PRICE_DATA_price_type', table_name='KB_PROPERTY_PRICE_DATA')
    op.drop_index('ix_KB_PROPERTY_PRICE_DATA_time_span', table_name='KB_PROPERTY_PRICE_DATA')
    op.drop_table('KB_PROPERTY_PRICE_DATA')
    op.drop_index('ix_KB_PREDICTION_date', table_name='KB_PREDICTION')
    op.drop_index('ix_KB_PREDICTION_id', table_name='KB_PREDICTION')
    op.drop_table('KB_PREDICTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KB_PREDICTION',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='KB_PREDICTION_pkey')
    )
    op.create_index('ix_KB_PREDICTION_id', 'KB_PREDICTION', ['id'], unique=False)
    op.create_index('ix_KB_PREDICTION_date', 'KB_PREDICTION', ['date'], unique=False)
    op.create_table('KB_PROPERTY_PRICE_DATA',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('index_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='KB_PROPERTY_PRICE_DATA_pkey')
    )
    op.create_index('ix_KB_PROPERTY_PRICE_DATA_time_span', 'KB_PROPERTY_PRICE_DATA', ['time_span'], unique=False)
    op.create_index('ix_KB_PROPERTY_PRICE_DATA_price_type', 'KB_PROPERTY_PRICE_DATA', ['price_type'], unique=False)
    op.create_index('ix_KB_PROPERTY_PRICE_DATA_id', 'KB_PROPERTY_PRICE_DATA', ['id'], unique=False)
    op.create_index('ix_KB_PROPERTY_PRICE_DATA_date', 'KB_PROPERTY_PRICE_DATA', ['date'], unique=False)
    op.create_table('kb_prediction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kb_prediction_pkey')
    )
    op.create_index('ix_kb_prediction_id', 'kb_prediction', ['id'], unique=False)
    op.create_index('ix_kb_prediction_date', 'kb_prediction', ['date'], unique=False)
    op.create_table('kb_region',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kb_region_pkey')
    )
    op.create_index('ix_kb_region_region_name', 'kb_region', ['region_name'], unique=True)
    op.create_index('ix_kb_region_id', 'kb_region', ['id'], unique=False)
    op.create_table('KB_REGION',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='KB_REGION_pkey')
    )
    op.create_index('ix_KB_REGION_region_name', 'KB_REGION', ['region_name'], unique=True)
    op.create_index('ix_KB_REGION_id', 'KB_REGION', ['id'], unique=False)
    op.create_table('kb_property_price_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('index_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kb_property_price_data_pkey')
    )
    op.create_index('ix_kb_property_price_data_time_span', 'kb_property_price_data', ['time_span'], unique=False)
    op.create_index('ix_kb_property_price_data_price_type', 'kb_property_price_data', ['price_type'], unique=False)
    op.create_index('ix_kb_property_price_data_id', 'kb_property_price_data', ['id'], unique=False)
    op.create_index('ix_kb_property_price_data_date', 'kb_property_price_data', ['date'], unique=False)
    # ### end Alembic commands ###
