"""Auto-generated migration

Revision ID: f1bb6c3dd74e
Revises: e9a6f14aa674
Create Date: 2024-09-27 16:13:39.024699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bb6c3dd74e'
down_revision: Union[str, None] = 'e9a6f14aa674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_property_price_data_date', table_name='property_price_data')
    op.drop_index('ix_property_price_data_id', table_name='property_price_data')
    op.drop_index('ix_property_price_data_price_type', table_name='property_price_data')
    op.drop_index('ix_property_price_data_time_span', table_name='property_price_data')
    op.drop_table('property_price_data')
    op.drop_index('ix_predictions_date', table_name='predictions')
    op.drop_index('ix_predictions_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_regions_id', table_name='regions')
    op.drop_index('ix_regions_region_name', table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='regions_pkey')
    )
    op.create_index('ix_regions_region_name', 'regions', ['region_name'], unique=True)
    op.create_index('ix_regions_id', 'regions', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='predictions_pkey')
    )
    op.create_index('ix_predictions_id', 'predictions', ['id'], unique=False)
    op.create_index('ix_predictions_date', 'predictions', ['date'], unique=False)
    op.create_table('property_price_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('index_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='property_price_data_pkey')
    )
    op.create_index('ix_property_price_data_time_span', 'property_price_data', ['time_span'], unique=False)
    op.create_index('ix_property_price_data_price_type', 'property_price_data', ['price_type'], unique=False)
    op.create_index('ix_property_price_data_id', 'property_price_data', ['id'], unique=False)
    op.create_index('ix_property_price_data_date', 'property_price_data', ['date'], unique=False)
    # ### end Alembic commands ###
