"""Auto-generated migration

Revision ID: f997ddc76b91
Revises: 31f8738ee080
Create Date: 2024-09-28 21:51:53.699574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f997ddc76b91'
down_revision: Union[str, None] = '31f8738ee080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kb_prediction_date', table_name='kb_prediction')
    op.drop_index('ix_kb_prediction_id', table_name='kb_prediction')
    op.drop_table('kb_prediction')
    op.drop_index('ix_kb_property_price_data_date', table_name='kb_property_price_data')
    op.drop_index('ix_kb_property_price_data_id', table_name='kb_property_price_data')
    op.drop_index('ix_kb_property_price_data_price_type', table_name='kb_property_price_data')
    op.drop_index('ix_kb_property_price_data_time_span', table_name='kb_property_price_data')
    op.drop_table('kb_property_price_data')
    op.drop_index('ix_kb_region_id', table_name='kb_region')
    op.drop_index('ix_kb_region_region_name', table_name='kb_region')
    op.drop_table('kb_region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_region',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('kb_region_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kb_region_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_kb_region_region_name', 'kb_region', ['region_name'], unique=True)
    op.create_index('ix_kb_region_id', 'kb_region', ['id'], unique=False)
    op.create_table('kb_property_price_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('index_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_interpolated', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['kb_region.id'], name='kb_property_price_data_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kb_property_price_data_pkey')
    )
    op.create_index('ix_kb_property_price_data_time_span', 'kb_property_price_data', ['time_span'], unique=False)
    op.create_index('ix_kb_property_price_data_price_type', 'kb_property_price_data', ['price_type'], unique=False)
    op.create_index('ix_kb_property_price_data_id', 'kb_property_price_data', ['id'], unique=False)
    op.create_index('ix_kb_property_price_data_date', 'kb_property_price_data', ['date'], unique=False)
    op.create_table('kb_prediction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_span', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['kb_region.id'], name='kb_prediction_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kb_prediction_pkey')
    )
    op.create_index('ix_kb_prediction_id', 'kb_prediction', ['id'], unique=False)
    op.create_index('ix_kb_prediction_date', 'kb_prediction', ['date'], unique=False)
    # ### end Alembic commands ###
