"""upgrade

Revision ID: ff5b985540ef
Revises: 09a4696dc534
Create Date: 2024-10-23 11:21:12.607925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5b985540ef'
down_revision: Union[str, None] = '09a4696dc534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('published_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'published_date')
    # ### end Alembic commands ###
